name = "DynamicalSystemsBase"
uuid = "6e36e845-645a-534a-86f2-f5d4aa5a06b4"
repo = "https://github.com/JuliaDynamics/DynamicalSystemsBase.jl.git"
version = "1.2.5"

[deps]
DelayEmbeddings = "5732040d-69e3-5649-938a-b6b4f237613f"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SimpleDiffEq = "05bca326-078c-5bf0-a5bf-ce7c7982d7fd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DiffEqBase = "5.0.0"
DiffEqCallbacks = "≥ 2.1.0"
ForwardDiff = "≥ 0.8.0"
OrdinaryDiffEq = "≥ 5.0.0"
Reexport = "≥ 0.1.0"
SimpleDiffEq = "≥ 0.3.0"
StaticArrays = "≥ 0.8.0"
julia = "≥ 1.0.0"

[extras]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DiffEqCallbacks", "Statistics", "LinearAlgebra", "SparseArrays", "OrdinaryDiffEq", "Test"]
